name: PHP-CS-Fixer

on:
  push:
    paths:
      - '**.php'
      - '.php-cs-fixer.dist.php'
  pull_request:
    paths:
      - '**.php'
      - '.php-cs-fixer.dist.php'


jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none
          tools: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2

      - name: Run PHP-CS-Fixer
        run: ./vendor/bin/php-cs-fixer fix --dry-run --show-progress=dots --using-cache=no --verbose
