name: Psalm

on:
  push:
    paths:
      - '**.php'
      - 'psalm.xml'
  pull_request:
    paths:
      - '**.php'
      - 'psalm.xml'


jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none
          tools: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2

      - name: Run Psalm
        run: ./vendor/bin/psalm --no-progress --shepherd --show-info=false --stats
